# -*- coding: utf-8 -*-
"""2_Drzewo_Decyzyjne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yFC2IHVCbK6ijXYq5D_8wcX-2G1-Dv8

Wczytanie bibliotek i zbiorów
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, recall_score, classification_report
from sklearn.model_selection import GridSearchCV

X_train = pd.read_csv('X_train.csv')
X_test = pd.read_csv('X_test.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

y_train = y_train.squeeze()
y_test = y_test.squeeze()

"""Analiza modelu"""

import numpy as np
from sklearn.metrics import (
    make_scorer,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    fbeta_score
)

def business_profit_score(y_true, y_pred):
    """
    Oblicza zysk biznesowy dla zadania.
    +1 za uratowane życie (True Positive - TP).
    -0.25 za utraconego pacjenta (False Positive - FP),
    ponieważ co czwarty fałszywy alarm pacjent odinstalowujący aplikację.
    """
    _, fp, _, tp = confusion_matrix(y_true, y_pred).ravel()

    return tp - (0.25 * fp)

# Tworzymy obiekt scorer gotowy do użycia
custom_business_scorer = make_scorer(business_profit_score, greater_is_better=True)

# Tworzymy osobną metrykę F2 do śledzenia (Czułość jest dla nas 2x ważniejsza)
f2_scorer = make_scorer(fbeta_score, beta=2)

# Słownik wszystkich metryk do wykorzystania w GridSearchCV (parametr: scoring=scoring_dict)
scoring_dict = {
    'Business_Score': custom_business_scorer,
    'F2_Score': f2_scorer,
    'ROC_AUC': 'roc_auc',
    'PR_AUC': 'average_precision'
}


def evaluate_heart_model(model, X_test, y_test):
    """
    Wypisuje pełny raport skuteczności modelu przetestowanego na zbiorze testowym.
    """
    y_pred = model.predict(X_test)

    # Pobieramy prawdopodobieństwa (potrzebne do ROC i PR AUC)
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
    else:
        # Fallback np. dla dec_function
        y_proba = model.decision_function(X_test)

    print("--- WYNIKI MODELU: SYSTEM OSTRZEGANIA PRZED ZAWAŁEM ---")
    print(f"Zysk Biznesowy (TP - 0.25*FP): {business_profit_score(y_test, y_pred):.2f}")
    print(f"F2-Score (Nacisk na Czułość):  {fbeta_score(y_test, y_pred, beta=2):.4f}")
    print(f"ROC AUC:                       {roc_auc_score(y_test, y_proba):.4f}")
    print(f"PR AUC (Average Precision):    {average_precision_score(y_test, y_proba):.4f}")
    print("\n--- SZCZEGÓŁOWY RAPORT KLASYFIKACJI ---")
    print(classification_report(y_test, y_pred))

"""Model bazowy (bez optymalizacji hiperparametrów)"""

tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

business_profit_score(y_test, y_pred)
evaluate_heart_model(tree, X_test, y_test)

"""Badania hiperparametrów i trening najlepszego modelu"""

# Wartości do zbadania
param_grid = {
    'max_depth': [3, 5, 7, 10, 15],
    'min_samples_leaf': [5, 10, 20],
    'class_weight': [
        'balanced',
        {0: 1, 1: 5},
        {0: 1, 1: 10}
    ]
}

base_tree = DecisionTreeClassifier(random_state=42)

# Optymalizujemy pod zysk biznesowy
grid_search = GridSearchCV(
    estimator=base_tree,
    param_grid=param_grid,
    scoring=scoring_dict,
    refit='Business_Score',
    cv=5,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)
best_tree = grid_search.best_estimator_

print("\nNajlepsze znalezione parametry:")
print(grid_search.best_params_)
print("-" * 50)


"""Ocena ostateczna"""
evaluate_heart_model(best_tree, X_test, y_test)

"""Wizualizacja"""

plt.figure(figsize=(20, 10))
plot_tree(best_tree,
          feature_names=X_train.columns,
          filled=True,
          rounded=True,
          fontsize=10,
          max_depth=3)

plt.title("Wizualizacja najlepszego drzewa decyzyjnego", fontsize=15)
plt.show()